# Network Setting
network:
  # address to listen
  # Example: ":443", "10.1.2.3:443"
  listen_address: ":443"
  # Convert client ipv4 address to dial source ipv6 address
  # 203.0.113.1 -> 2001:db8:3:4:5:6:cb00:7101
  use_address_conversion: true
  # if you use address conversion, last 32 bits must be zero
  # Example: "2001:db8:3:4:5:6::", "2001:db8:3:4:5:6:7:8"(if not use address conversion), ""(automatic)
  dial_source_address: "2001:db8:3:4:5:6::"
  # which port forward to
  remote_port: 443

# destination hostname setting
# please comment in least one option
# Please look README for further infomation
allow_rule:
  # IPv4 record
  ipv4_addr:
    # - "192.0.2.0/24"
    # - "203.0.113.1/32"

  # Domain whitelist
  domain:
    plain:
      # - "example.com"
    regex:
      # - '^(.*\.)?example\.com\.?$'

deny_rule:
  # Add them your local network if you don't want to access your local network
  ipv6_addr:
    - "::1/128" # Loopback Address
    - "fe00::/7" # Unique-Local
    - "fe80::/10" # Link-Local Unicast
    # - "2001:db8:3::/56"

# Buffer size for Client Hello packet
# You don't have to change this usually
handshake_buffer: 4096

# Enable debug log
debug: false
